### ISSUE TITLE
KeyError: 'ID'

### ISSUE THREAD

**Issue by PunicagranatumL** [chengcz/pyGTF#1]
When use pyGTF,  i Encountered KeyError: 'ID'
my code 

import sys
from pyGTF import Transcript
from pyGTF import GTFReader
with GTFReader('A.gtf',flag_stream=True) as fi:
    for i in fi:
        print(i.summary)
        
INFO  @ pyGTF.py:1277, 2020-07-18 10:07:08,861, Skip Known Annotation Feature: 
    (biological_region, stop_codon, gene, Selenocysteine, start_codon, pseudogene, chromosome, ncRNA_gene)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-101-c998f1dfc455> in <module>()
      1 with GTFReader('A.gtf',flag_stream=True) as fi:
----> 2     for i in fi:
      3         print(i.summary)
      4 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pygtf-0.1.1-py3.6.egg\pyGTF.py in __iter__(self)
   1191     def __iter__(self):
   1192         Iterator = self.__stream_mode() if self._flag_stream else self.__store_mode()
-> 1193         for trans in Iterator:
   1194             _transid, _chro, _interval, _strand, _exon, _cds, _utr, _attr = trans
   1195             _attr = {

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pygtf-0.1.1-py3.6.egg\pyGTF.py in __stream_mode(self)
   1205         '''
   1206         t_id, t_exon, t_cds, t_utr, t_info = None, Interval(), Interval(), Interval(), {}
-> 1207         for line in self.__read_gtf():
   1208             chro, _, feature, start, end, _, strand, _, attr, line_id = line
   1209 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pygtf-0.1.1-py3.6.egg\pyGTF.py in __read_gtf(self)
   1291                 attr = [x.strip().partition('=') for x in attr.split(';') if x.strip()]
   1292                 attr = {x[0]: x[2].strip('\'\t\n\r"') for x in attr}
-> 1293                 line_id = attr['ID'] if feature in self._transcript_feature else attr['Parent']
   1294             else:
   1295                 attr = [x.strip().partition(' ') for x in attr.split(';') if x.strip()]

KeyError: 'ID'

A.gtf

NC_012007.3	StringTie	transcript	10713	27534	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; gene_name "LOC104879287"; oId "STRG.2.1"; cmp_ref "XR_785793.2"; class_code "="; tss_id "TSS42"; num_samples "4";
NC_012007.3	StringTie	exon	10713	10945	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "1";
NC_012007.3	StringTie	exon	12426	12529	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "2";
NC_012007.3	StringTie	exon	12628	12700	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "3";
NC_012007.3	StringTie	exon	12798	12859	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "4";
NC_012007.3	StringTie	exon	12997	13119	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "5";
NC_012007.3	StringTie	exon	26528	26632	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "6";
NC_012007.3	StringTie	exon	26733	27534	.	+	.	transcript_id "TCONS_00003418"; gene_id "XLOC_000004"; exon_number "7";

**Comment by PunicagranatumL** [comment]
This problem has been solved. comment out the code in 1290-1294 line of pyGTF.py and then reinstall. python setup.py install.
https://www.jianshu.com/p/0e601265589f

**Comment by chengcz** [comment]
1. “line:1290  if '=' in attr: ” , this Code is used to judge the file format, GTF or GFF?  
2. do not consider the case where the attribute value includes "=", debug line 1290 to "if all(map(lambda x: '=' in x, [x for x in attr.split(';') if x.strip()])):"

@PunicagranatumL

**Comment by chengcz** [comment]
fix
